# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20160727_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='work_area',
        ),
        migrations.AddField(
            model_name='workplace',
            name='description',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='workplace',
            name='work_area',
            field=models.CharField(choices=[('DS', 'Downstairs'), ('US', 'Upstairs')], default='DS', max_length=2),
        ),
        migrations.AlterField(
            model_name='membership',
            name='workgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Workplace'),
        ),
    ]
